# This file is modified based on https://github.com/huggingface/transformers/blob/v4.52.4/src/transformers/models/qwen3/modeling_qwen3.py.
#
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/qwen3/modular_qwen3.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_qwen3.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2025 The Qwen team, Alibaba Group and the HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Callable, Optional, Tuple, Union

import torch
from torch import nn
import flashinfer
from transformers.activations import ACT2FN
from transformers.cache_utils import Cache, DynamicCache, SlidingWindowCache, StaticCache
from transformers.generation import GenerationMixin
from transformers.integrations import use_kernel_forward_from_hub
from transformers.modeling_attn_mask_utils import AttentionMaskConverter
from transformers.modeling_flash_attention_utils import FlashAttentionKwargs
from transformers.modeling_layers import GradientCheckpointingLayer
from transformers.modeling_outputs import (
    BaseModelOutputWithPast,
    CausalLMOutputWithPast,
    QuestionAnsweringModelOutput,
    SequenceClassifierOutputWithPast,
    TokenClassifierOutput,
)
from transformers.modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from transformers.modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from transformers.processing_utils import Unpack
from transformers.utils import LossKwargs, auto_docstring, can_return_tuple, is_torch_flex_attn_available, logging
from .configuration_sdar import SDARConfig
import time
import math
from flash_attn.ops.triton.layer_norm import rms_norm_fn as flash_rms_norm
from einops import rearrange
import torch.nn.functional as F
try:
    from flash_attn import flash_attn_func, flash_attn_varlen_func, flash_attn_varlen_qkvpacked_func, flash_attn_varlen_kvpacked_func
    from flash_attn.bert_padding import index_first_axis, pad_input, unpad_input
except:
    pass

try:
    from liger_kernel.ops.swiglu import LigerSiLUMulFunction  # noqa: F401
    liger_kernel_is_available = True
except ImportError:
    liger_kernel_is_available = False
from torch.nn.attention.flex_attention import create_block_mask, flex_attention
import torch._dynamo
# torch._dynamo.config.suppress_errors = True
torch._dynamo.config.cache_size_limit = 10000
torch._dynamo.config.accumulated_cache_size_limit = 10000


def create_block_mask_cached(score_mod, B, H, M, N, device="cuda", _compile=True):
    return create_block_mask(
        score_mod,
        B,
        H,
        M,
        N,
        device=device,
        _compile=_compile,
    )


def customize_mask(mask, block_size=128):
    def process(b, h, q_idx, kv_id):
        return mask[b, h, q_idx // block_size, kv_id // block_size]
    return process

if is_torch_flex_attn_available():
    from torch.nn.attention.flex_attention import BlockMask, create_block_mask, flex_attention
    from transformers.integrations.flex_attention import make_flex_block_causal_mask


logger = logging.get_logger(__name__)


@use_kernel_forward_from_hub("RMSNorm")
class SDARRMSNorm(nn.Module):
    def __init__(self, hidden_size, eps=1e-6):
        """
        SDARRMSNorm is equivalent to T5LayerNorm
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states):
        return flash_rms_norm(
            hidden_states, weight=self.weight, bias=None, eps=self.variance_epsilon)
        '''
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * \
            torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)
        '''

    def extra_repr(self):
        return f"{tuple(self.weight.shape)}, eps={self.variance_epsilon}"


class SDARMLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size
        self.intermediate_size = config.intermediate_size
        self.gate_proj = nn.Linear(
            self.hidden_size, self.intermediate_size, bias=False)
        self.up_proj = nn.Linear(
            self.hidden_size, self.intermediate_size, bias=False)
        self.down_proj = nn.Linear(
            self.intermediate_size, self.hidden_size, bias=False)
        self.act_fn = ACT2FN[config.hidden_act]

    def forward(self, x):
        if liger_kernel_is_available:
            return self.down_proj(LigerSiLUMulFunction.apply(self.gate_proj(x), self.up_proj(x)))
        else:
            down_proj = self.down_proj(self.act_fn(
                self.gate_proj(x)) * self.up_proj(x))
            return down_proj


def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2:]
    return torch.cat((-x2, x1), dim=-1)


def apply_rotary_pos_emb(q, k, cos, sin, position_ids=None, unsqueeze_dim=1):
    """Applies Rotary Position Embedding to the query and key tensors.
    Args:
        q (`torch.Tensor`): The query tensor.
        k (`torch.Tensor`): The key tensor.
        cos (`torch.Tensor`): The cosine part of the rotary embedding.
        sin (`torch.Tensor`): The sine part of the rotary embedding.
        position_ids (`torch.Tensor`, *optional*):
            Deprecated and unused.
        unsqueeze_dim (`int`, *optional*, defaults to 1):
            The 'unsqueeze_dim' argument specifies the dimension along which to unsqueeze cos[position_ids] and
            sin[position_ids] so that they can be properly broadcasted to the dimensions of q and k. For example, note
            that cos[position_ids] and sin[position_ids] have the shape [batch_size, seq_len, head_dim]. Then, if q and
            k have the shape [batch_size, heads, seq_len, head_dim], then setting unsqueeze_dim=1 makes
            cos[position_ids] and sin[position_ids] broadcastable to the shapes of q and k. Similarly, if q and k have
            the shape [batch_size, seq_len, heads, head_dim], then set unsqueeze_dim=2.
    Returns:
        `tuple(torch.Tensor)` comprising of the query and key tensors rotated using the Rotary Position Embedding.
    """
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(
        batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)

def split_attention_outputs(
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attn_mask: torch.Tensor = None,
    scale: float = None,
):
    """
    返回 query 对历史 KV cache 与当前 tokens 的 attention 输出。
    
    Args:
        query: [B, H, Q, D]
        key: [B, H, K, D]   (K = past_len + Q)
        value: [B, H, K, D]
        attn_mask: [B, 1, Q, K] 或 None
        scale: float，通常为 1 / sqrt(D)
    
    Returns:
        attn_output_past: [B, H, Q, D]
        attn_output_current: [B, H, Q, D]
    """
    B, H, Q, D = query.shape
    K = key.size(2)
    past_len = K - Q
    if scale is None:
        scale = 1.0 / (D ** 0.5)
    
    # 计算完整 attention 分数
    attn_scores = torch.matmul(query, key.transpose(-2, -1)) * scale
    if attn_mask is not None:
        attn_scores = attn_scores + attn_mask
    attn_weights = F.softmax(attn_scores, dim=-1)

    # 拆分权重
    attn_weights_past = attn_weights[..., :past_len]
    attn_weights_current = attn_weights[..., past_len:]

    # 计算两部分输出
    attn_output_past = torch.matmul(attn_weights_past, value[:, :, :past_len, :])
    attn_output_current = torch.matmul(attn_weights_current, value[:, :, past_len:, :])

    return attn_output_past, attn_output_current

def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: Optional[torch.Tensor],
    scaling: float,
    dropout: float = 0.0,
    **kwargs,
):
    key_states = repeat_kv(key, module.num_key_value_groups)
    value_states = repeat_kv(value, module.num_key_value_groups)

    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling
    if attention_mask is not None:
        causal_mask = attention_mask[:, :, :, : key_states.shape[-2]]
        attn_weights = attn_weights + causal_mask

    attn_weights = nn.functional.softmax(
        attn_weights, dim=-1, dtype=torch.float32).to(query.dtype)
    attn_weights = nn.functional.dropout(
        attn_weights, p=dropout, training=module.training)
    attn_output = torch.matmul(attn_weights, value_states)
    attn_output = attn_output.transpose(1, 2).contiguous()

    return attn_output, attn_weights

import torch
import torch.nn.functional as F

import torch
import torch.nn.functional as F

def exact_flash_attn_func(q, k, v, dropout_p=0.0, softmax_scale=None,
                          causal=False, window_size=(-1, -1), softcap=0.0,
                          alibi_slopes=None, deterministic=True,
                          return_attn_probs=False):
    """
    计算阶段统一用 float32，最后按输入 dtype 返回。
    形状与 flash_attn_func 保持一致：
        q: (B, S_q, H, D)
        k,v: (B, S_k, H_k, D)
    返回:
        out: (B, S_q, H, D)
        logsumexp: (B, H, S_q)
        probs_or_None: (仅测试时) (B,H,S_q,S_k)
    """
    B, S_q, H, D = q.shape
    S_k = k.shape[1]; Hk = k.shape[2]
    in_dtype = q.dtype
    device = q.device

    if softmax_scale is None:
        softmax_scale = 1.0 / (D ** 0.5)
    softmax_scale = float(softmax_scale)

    # 升精度到 fp32 并换到 (B,H,S,D)
    q32 = q.transpose(1, 2).to(torch.float32)          # (B,H,S_q,D)
    k32 = k.transpose(1, 2).to(torch.float32)          # (B,Hk,S_k,D)
    v32 = v.transpose(1, 2).to(torch.float32)          # (B,Hk,S_k,D)

    # MQA/GQA: 扩 KV 头到与 Q 一致
    if Hk != H:
        assert H % Hk == 0, "Q heads must be multiple of KV heads"
        rep = H // Hk
        k32 = k32.repeat_interleave(rep, dim=1)        # (B,H,S_k,D)
        v32 = v32.repeat_interleave(rep, dim=1)

    # 得分 (B,H,S_q,S_k)
    scores = torch.matmul(q32, k32.transpose(-2, -1)) * softmax_scale

    # 可选: causal mask
    if causal:
        # 注意：这里的因果对齐按 SDPA 语义；如果你有自定义mask，按需替换
        # S_q ≤ S_k 时等价于标准下三角
        mask = torch.tril(torch.ones(S_q, S_k, device=device, dtype=torch.bool))
        scores = scores.masked_fill(~mask, float('-inf'))

    # logsumexp 与 softmax（全在 fp32）
    L = torch.logsumexp(scores, dim=-1)                # (B,H,S_q)
    probs = torch.softmax(scores, dim=-1)              # (B,H,S_q,S_k)

    if dropout_p and dropout_p > 0.0:
        probs = F.dropout(probs, p=dropout_p)

    out32 = torch.matmul(probs, v32)                   # (B,H,S_q,D)

    # 回到 (B,S_q,H,D) 与输入 dtype
    out = out32.transpose(1, 2).contiguous()
    if return_attn_probs:
        return out, L, probs
    else:
        return out, L, None

import matplotlib.pyplot as plt
import numpy as np
import os

def save_attention_map(
    attn: torch.Tensor,
    save_path: str,
    *,
    cmap: str = "viridis",
    vmin: Optional[float] = None,
    vmax: Optional[float] = None,
    normalize: bool = False,
    interpolation: str = "nearest",
    show_colorbar: bool = True,
    dpi: int = 300,
    pad_inches: float = 0.02,
    grid: bool = False,
) -> None:
    """
    将二维注意力图（attention map）保存为热力图图片。

    参数:
        attn: PyTorch Tensor。期望是 (H, W)。也容忍以下形状之一：
              - (1, H, W)
              - (H, W, 1)
              - (B, H, W) -> 取第 0 个
              - (C, H, W) -> 取第 0 个通道
              - (B, C, H, W) -> 取第 0 个 batch 与第 0 个通道
            会自动 .detach().cpu() 并处理 NaN/Inf。
        save_path: 输出图片保存路径（包含文件名），如 "out/attn.png"。
        cmap: Matplotlib 颜色映射，如 "magma" / "viridis" / "plasma" 等。
        vmin, vmax: 颜色范围；若为 None 则由数据自动决定。若 normalize=True，
            则会将数据线性拉伸到 [0, 1] 再渲染，vmin/vmax 将被忽略。
        normalize: 是否将数据归一化到 [0, 1]（对对比度更友好）。
        interpolation: imshow 的插值方式，如 "nearest"、"bilinear"。
        show_colorbar: 是否显示颜色条。
        dpi: 保存图片的分辨率（dots per inch）。
        pad_inches: 保存时边缘留白。
        grid: 是否显示网格（调试像素时有用）。

    返回:
        None（直接将图片写入 save_path）。
    """
    if not isinstance(attn, torch.Tensor):
        raise TypeError(f"`attn` must be a torch.Tensor, got {type(attn)}")

    # 移到 CPU，去梯度，处理异常值
    t = attn.detach().to("cpu")
    t = torch.nan_to_num(t, nan=0.0, posinf=0.0, neginf=0.0)

    # 尝试从常见形状中提取 (H, W)
    if t.ndim == 2:
        pass
    elif t.ndim == 3:
        # (C,H,W) 或 (H,W,1) 或 (B,H,W)
        if t.shape[-1] == 1 and t.permute(2, 0, 1).shape[0] == 1:  # (H,W,1) -> squeeze
            t = t.squeeze(-1)
        else:
            t = t[0]  # 取第 0 个通道或 batch
            if t.ndim != 2:
                raise ValueError(f"Cannot infer (H,W) from shape {tuple(attn.shape)}")
    elif t.ndim == 4:
        # 假定 (B, C, H, W)
        t = t[0, 0]
    else:
        raise ValueError(f"Unsupported tensor ndim={t.ndim}, shape={tuple(attn.shape)}")

    if t.ndim != 2:
        raise ValueError(f"Expected 2D map; got shape {tuple(t.shape)}")

    arr = t.float().numpy()

    # 归一化（可选）
    if normalize:
        a_min = float(np.min(arr))
        a_max = float(np.max(arr))
        if a_max > a_min:
            arr = (arr - a_min) / (a_max - a_min)
        else:
            arr = np.zeros_like(arr, dtype=np.float32)  # 常数图的极端情况

    # 准备保存目录
    os.makedirs(os.path.dirname(save_path) or ".", exist_ok=True)

    # 绘制与保存
    fig = plt.figure(figsize=(6, 6), dpi=dpi)
    ax = plt.axes([0, 0, 1, 1])  # 去掉边框与坐标轴占位
    ax.set_axis_off()

    im = ax.imshow(
        arr,
        cmap=cmap,
        interpolation=interpolation,
        # 若 normalize=True 已标准化，此处忽略 vmin/vmax
        vmin=None if normalize else vmin,
        vmax=None if normalize else vmax,
        aspect="equal",
        origin="upper",
    )

    if grid:
        ax.set_axis_on()
        ax.grid(True, linewidth=0.3)

    if show_colorbar:
        # 为了紧凑，单独创建一个窄色条轴
        from mpl_toolkits.axes_grid1 import make_axes_locatable
        divider = make_axes_locatable(ax)
        cax = divider.append_axes("right", size="3%", pad=0.02)
        cb = plt.colorbar(im, cax=cax)
        cb.outline.set_linewidth(0.3)
        cb.ax.tick_params(labelsize=8)

    plt.savefig(save_path, bbox_inches="tight", pad_inches=pad_inches)
    plt.close(fig)

import torch

def compute_attention_score(q, k, scale=None, causal=False):
    """
    计算 attention score（softmax(q·kᵀ / sqrt(D))）

    参数:
        q: [B, Q, H, D]
        k: [B, Q, H, D]
        scale: 缩放因子 (默认 1/sqrt(D))
        causal: 是否使用 causal mask

    返回:
        attn_scores: [B, H, Q, Q]
    """
    B, Q, H, D = q.shape
    if scale is None:
        scale = 1.0 / (D ** 0.5)

    # 调整维度以便做矩阵乘法
    q = q.permute(0, 2, 1, 3)  # [B, H, Q, D]
    k = k.permute(0, 2, 1, 3)  # [B, H, Q, D]

    # QKᵀ
    attn_logits = torch.matmul(q, k.transpose(-2, -1)) * scale  # [B, H, Q, Q]

    # 可选 causal mask（下三角）
    if causal:
        mask = torch.triu(
            torch.ones(Q, Q, device=q.device, dtype=torch.bool),
            diagonal=1
        )
        attn_logits = attn_logits.masked_fill(mask, float('-inf'))

    # softmax 得到注意力权重
    attn_scores = torch.softmax(attn_logits, dim=-1)
    return attn_scores

def compute_token_influence(q, k, scale=None, last_n=None):
    """
    计算 query tokens 对所有 key tokens 的注意力影响（统计时排除自己）。

    参数:
        q: [B, Q, H, D]
        k: [B, K, H, D]
        scale: 缩放因子 (通常为 1/sqrt(D))
        last_n: 只取最后 n 个 query 的影响（例如 query_states.shape[2]）

    返回:
        influence: [last_n] (或 [Q] 如果未指定 last_n)
    """
    B, H, Q, D = q.shape
    K = k.shape[2]

    if scale is None:
        scale = 1.0 / (D ** 0.5)

    # QKᵀ -> [B, H, Q, K]
    attn_logits = torch.matmul(q, k.transpose(-2, -1)) * scale
    attn_scores = torch.softmax(attn_logits, dim=-1)

    # -------- 排除 self 的统计项（仅在统计阶段）--------
    # 当 Q != K 时，通常最后 Q 个 query 对应最后 Q 个 key
    # 所以我们只排除这些对应的 diagonal 部分
    if K >= Q:
        offset = K - Q
        mask = torch.arange(Q, device=q.device)
        self_idx = mask + offset  # 对齐最后 Q 个 token
        # 创建 mask，排除这些位置
        mask_matrix = torch.zeros(Q, K, device=q.device, dtype=torch.bool)
        mask_matrix[torch.arange(Q), self_idx] = True
        attn_scores = attn_scores.masked_fill(mask_matrix.unsqueeze(0).unsqueeze(0), 0)

    # 聚合统计（head 维和 key 维）
    influence = attn_scores.mean(1).mean(1)[0]  # [Q]

    if last_n is not None:
        influence = influence[-last_n:]

    return influence

def assign_sparse_tokens(veri_attn_output, current_attn_output, dirty_token_lists):
    """
    无 for 循环矢量化地在 veri_attn_output 中替换指定 token，
    支持输入形状 [B, T, H, D]。
    自动处理 dtype 不一致问题。
    """
    device = veri_attn_output.device
    B, T, H, D = veri_attn_output.shape

    # === 1. 将不规则索引展开成扁平张量 ===
    all_idx = torch.tensor([i for sub in dirty_token_lists for i in sub], device=device, dtype=torch.long)
    counts = torch.tensor([len(sub) for sub in dirty_token_lists], device=device, dtype=torch.long)
    max_len = counts.max()
    batch_idx = torch.arange(B, device=device).repeat_interleave(counts)

    # === 2. 构造 padded 索引矩阵 [B, max_len] ===
    dirty_tokens = torch.full((B, max_len), -1, dtype=torch.long, device=device)
    pos = torch.arange(max_len, device=device).repeat(B)
    mask = pos < counts.repeat_interleave(max_len)
    dirty_tokens = dirty_tokens.clone()
    dirty_tokens[batch_idx, pos[mask]] = all_idx

    # === 3. 扩展成 [B, max_len, H, D]，在第 1 维 (token 维) 上操作 ===
    index_expanded = dirty_tokens.unsqueeze(-1).unsqueeze(-1).expand(-1, -1, H, D)

    # === 4. gather 当前值 ===
    selected = current_attn_output.gather(1, index_expanded)

    # === ✅ 修复 dtype 不匹配 ===
    if selected.dtype != veri_attn_output.dtype:
        selected = selected.to(veri_attn_output.dtype)

    # === 5. scatter 写回 ===
    updated = veri_attn_output.scatter(1, index_expanded, selected)

    return updated

def create_dirty_mask(attn_output_past, dirty_tokens):
    """
    高效清零指定的 head 通道 (第二维)，无 Python for 循环。
    attn_output_past: [B, H, N, D]
    dirty_tokens: list[list[int]]，每个 batch 的 dirty head 索引
    """
    B, H, N, D = attn_output_past.shape
    # 构造 mask，True 表示该 head 需要清零
    mask = torch.zeros((B, H), dtype=torch.bool, device=attn_output_past.device)
    
    # 用 advanced indexing 一次性填充 True
    # 将 dirty_tokens 展平成索引对
    batch_idx = torch.arange(B, device=attn_output_past.device)
    all_b = []
    all_h = []
    for b, dirty in enumerate(dirty_tokens):
        if dirty:
            all_b.extend([b] * len(dirty))
            all_h.extend(dirty)
    if all_b:  # 避免空情况
        mask[torch.tensor(all_b, device=attn_output_past.device),
             torch.tensor(all_h, device=attn_output_past.device)] = True
    
    return mask

def zero_dirty_tokens(attn_output_past, dirty_tokens):
    """
    高效清零指定的 head 通道 (第二维)，无 Python for 循环。
    attn_output_past: [B, H, N, D]
    dirty_tokens: list[list[int]]，每个 batch 的 dirty head 索引
    """
    B, H, N, D = attn_output_past.shape
    # 构造 mask，True 表示该 head 需要清零
    mask = torch.zeros((B, H), dtype=torch.bool, device=attn_output_past.device)
    
    # 用 advanced indexing 一次性填充 True
    # 将 dirty_tokens 展平成索引对
    batch_idx = torch.arange(B, device=attn_output_past.device)
    all_b = []
    all_h = []
    for b, dirty in enumerate(dirty_tokens):
        if dirty:
            all_b.extend([b] * len(dirty))
            all_h.extend(dirty)
    if all_b:  # 避免空情况
        mask[torch.tensor(all_b, device=attn_output_past.device),
             torch.tensor(all_h, device=attn_output_past.device)] = True
    
    # 扩展 mask 形状为 [B, H, 1, 1] 以便广播
    attn_output_past = attn_output_past.masked_fill(mask[:, :, None, None], 0)
    return attn_output_past

def mask_last_c_ones(attention_mask: torch.Tensor, c: int) -> torch.Tensor:
    """
    将每个样本中最后 c 个 1 改为 0。

    参数:
        attention_mask: [B, L], 值为 0/1 的张量
        c: 要屏蔽的最后几个 1 的数量
    返回:
      new_mask: [B, L], 修改后的 mask
    """
    if attention_mask.dim() == 4:
        new_mask = attention_mask.clone()
        new_mask[..., -c:] = 0
        return new_mask

    if len(attention_mask.shape)>2:
        attention_mask=attention_mask[:,0]
    B, L = attention_mask.shape
    device = attention_mask.device

    # 每个样本的有效长度（1 的数量）
    counts = attention_mask.sum(dim=1)  # [B]

    # 找出每个样本最后一个 1 的下标
    idx = torch.arange(L, device=device).unsqueeze(0).expand(B, -1)  # [B, L]

    # 计算每个位置到最后一个 1 的距离
    dist_from_end = counts.unsqueeze(1) - idx - 1  # [B, L]

    # 构造 mask：当 dist_from_end 在 [0, c) 时，说明是最后 c 个 1
    to_zero = (dist_from_end >= 0) & (dist_from_end < c) & (attention_mask == 1)

    # 应用修改
    new_mask = attention_mask.clone()
    new_mask[to_zero] = 0

    return new_mask

import torch
from einops import rearrange
from flash_attn import flash_attn_varlen_kvpacked_func


def forward_flash_attn_dirty(
    query_states,     # [B, Q, H, D]
    key_states,       # [B, K, H, D]
    value_states,     # [B, K, H, D]
    attention_mask,   # [B, K]  (1 = valid)
    dirty_lists,      # List[List[int]]  indices in [0, Q)
    softmax_scale,
):
    """
    dirty query: can only attend to block KV
    clean query: can attend to kv cache + block
    """

    device = query_states.device
    dtype = query_states.dtype

    B, Q, H, D = query_states.shape
    _, K, _, _ = key_states.shape

    # ------------------------------------------------------------
    # Step 1. 计算 kv / block 边界
    # ------------------------------------------------------------
    seqlens_k = attention_mask.sum(dim=-1).to(torch.int32)  # [B]
    kv_lens = seqlens_k - Q                                 # [B]
    max_seqlen_k = int(seqlens_k.max())

    # ------------------------------------------------------------
    # Step 2. 构造 clean / dirty Q（保持 batch 维）
    # ------------------------------------------------------------
    clean_q = torch.zeros_like(query_states)
    dirty_q = torch.zeros_like(query_states)

    clean_lens = torch.zeros(B, dtype=torch.int32, device=device)
    dirty_lens = torch.zeros(B, dtype=torch.int32, device=device)

    clean_pos = []   # (b, new_idx) -> original q_idx
    dirty_pos = []

    for b in range(B):
        dirty_set = set(dirty_lists[b])
        c = 0
        d = 0
        for q_idx in range(Q):
            if q_idx in dirty_set:
                dirty_q[b, d] = query_states[b, q_idx]
                dirty_pos.append((b, d, q_idx))
                d += 1
            else:
                clean_q[b, c] = query_states[b, q_idx]
                clean_pos.append((b, c, q_idx))
                c += 1
        clean_lens[b] = c
        dirty_lens[b] = d

    # ------------------------------------------------------------
    # Step 3. 构造 KV packed（完整 kv：cache + block）
    # ------------------------------------------------------------
    kv = torch.stack([key_states, value_states], dim=2)  # [B, K, 2, H, D]
    kv_packed = rearrange(kv, "b k two h d -> (b k) two h d")
    kv_packed = kv_packed[attention_mask.bool().flatten()]

    cu_seqlens_k = torch.cat([
        torch.zeros(1, device=device, dtype=torch.int32),
        seqlens_k.cumsum(0).to(torch.int32)
    ])

    # ------------------------------------------------------------
    # Step 4. CLEAN PASS（能看 kv cache + block）
    # ------------------------------------------------------------
    out = torch.zeros_like(query_states)
    logsumexp_out = torch.zeros(B, Q, H, device=device, dtype=dtype)

    if clean_lens.sum() > 0:
        cu_seqlens_q = torch.cat([
            torch.zeros(1, device=device, dtype=torch.int32),
            clean_lens.cumsum(0).to(torch.int32)
        ])

        q_clean_packed = rearrange(clean_q, "b q h d -> (b q) h d")
        q_clean_packed = q_clean_packed[
            torch.arange(B, device=device).repeat_interleave(clean_lens)
        ]

        out_clean, lse_clean, _ = flash_attn_varlen_kvpacked_func(
            q_clean_packed,
            kv_packed,
            cu_seqlens_q,
            cu_seqlens_k,
            max_seqlen_q=Q,
            max_seqlen_k=max_seqlen_k,
            dropout_p=0.0,
            softmax_scale=softmax_scale,
            causal=False,
            return_attn_probs=True,
        )

        # scatter 回原位置
        idx = 0
        for b, new_q, orig_q in clean_pos:
            out[b, orig_q] = out_clean[idx]
            logsumexp_out[b, orig_q] = lse_clean[idx]
            idx += 1

    # ------------------------------------------------------------
    # Step 5. DIRTY PASS（只能看 block KV）
    # ------------------------------------------------------------
    if dirty_lens.sum() > 0:
        # 构造 block-only KV
        kv_blocks = []
        block_lens = torch.zeros(B, dtype=torch.int32, device=device)

        for b in range(B):
            if dirty_lens[b] > 0:
                start = kv_lens[b]
                end = seqlens_k[b]
                kv_blocks.append(
                    torch.stack(
                        [key_states[b, start:end],
                         value_states[b, start:end]],
                        dim=1
                    )  # [Q, 2, H, D]
                )
                block_lens[b] = Q

        kv_blocks = torch.cat(kv_blocks, dim=0)

        cu_seqlens_k_blk = torch.cat([
            torch.zeros(1, device=device, dtype=torch.int32),
            block_lens.cumsum(0)
        ])

        cu_seqlens_q_blk = torch.cat([
            torch.zeros(1, device=device, dtype=torch.int32),
            dirty_lens.cumsum(0)
        ])

        q_dirty_packed = rearrange(dirty_q, "b q h d -> (b q) h d")
        q_dirty_packed = q_dirty_packed[
            torch.arange(B, device=device).repeat_interleave(dirty_lens)
        ]

        out_dirty, lse_dirty, _ = flash_attn_varlen_kvpacked_func(
            q_dirty_packed,
            kv_blocks,
            cu_seqlens_q_blk,
            cu_seqlens_k_blk,
            max_seqlen_q=Q,
            max_seqlen_k=Q,
            dropout_p=0.0,
            softmax_scale=softmax_scale,
            causal=False,
            return_attn_probs=True,
        )

        idx = 0
        for b, new_q, orig_q in dirty_pos:
            out[b, orig_q] = out_dirty[idx]
            logsumexp_out[b, orig_q] = lse_dirty[idx]
            idx += 1

    return out, logsumexp_out

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import font_manager

def visualize_attention_maps(attn_maps, title, save_path, cmap="viridis"):

    font_path = os.environ.get("TRADO_FONT_PATH")
    font_kwargs = {"fname": font_path} if font_path else {}

    title_font = font_manager.FontProperties(
        size=18, weight="bold", **font_kwargs
    )
    step_font = font_manager.FontProperties(
        size=16, weight="bold", **font_kwargs
    )
    cbar_font_size = 14

    attn_maps = [
        a.detach().cpu().numpy() if hasattr(a, "detach") else np.array(a)
        for a in attn_maps
    ]

    num_maps = len(attn_maps)

    fig = plt.figure(figsize=(2.6 * num_maps + 0.8, 3))

    gs = fig.add_gridspec(
        1, num_maps + 2,
        width_ratios=[0.18] + [1] * num_maps + [0.05]
    )
    gs.update(wspace=0.03)

    # ---- 左侧标题 ----
    ax_title = fig.add_subplot(gs[0, 0])
    ax_title.text(
        0.98, 0.5,
        title,
        ha="right",
        va="center",
        fontproperties=title_font
    )
    ax_title.axis("off")

    # ---- Attention maps + Step ----
    vmin = min(a.min() for a in attn_maps)
    vmax = max(a.max() for a in attn_maps)

    im = None
    for i, attn in enumerate(attn_maps):
        ax = fig.add_subplot(gs[0, i + 1])
        im = ax.imshow(attn, cmap=cmap, vmin=vmin, vmax=vmax)
        ax.axis("off")

        ax.text(
            0.5, -0.005,
            f"Step {i+1}-Step {i+2}",
            ha="center",
            va="top",
            transform=ax.transAxes,
            fontproperties=step_font
        )

    # ---- Color bar ----
    cax = fig.add_subplot(gs[0, -1])
    cbar = plt.colorbar(im, cax=cax)
    cbar.ax.tick_params(labelsize=cbar_font_size)
    for tick in cbar.ax.get_yticklabels():
        tick.set_fontproperties(title_font)

    fig.subplots_adjust(
        left=0.01,
        right=0.99,
        top=0.96,
        bottom=0.06
    )

    plt.savefig(save_path, dpi=300, bbox_inches="tight", pad_inches=0.02)
    plt.close(fig)

class SDARAttention(nn.Module):
    """Multi-headed attention from 'Attention Is All You Need' paper"""

    def __init__(self, config: SDARConfig, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.head_dim = getattr(
            config, "head_dim", config.hidden_size // config.num_attention_heads)
        self.num_key_value_groups = config.num_attention_heads // config.num_key_value_heads
        self.scaling = self.head_dim**-0.5
        self.attention_dropout = config.attention_dropout
        self.is_causal = True

        self.hidden_size = config.hidden_size
        self.num_attention_heads = config.num_attention_heads
        self.num_key_value_heads = config.num_key_value_heads
        self.attn_output_=None
        self.coses=[]
        self.coses_per_head=[]
        self.cur_attn_output=None
        self.past_attn_output=None
        self.cos_cures=[]
        self.cos_cures_per_head=[]

        self.q_proj = nn.Linear(
            config.hidden_size, config.num_attention_heads * self.head_dim, bias=config.attention_bias
        )
        self.k_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.v_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.o_proj = nn.Linear(
            config.num_attention_heads * self.head_dim, config.hidden_size, bias=config.attention_bias
        )
        # unlike olmo, only on the head dim!
        self.q_norm = SDARRMSNorm(self.head_dim, eps=config.rms_norm_eps)
        # thus post q_norm does not need reshape
        self.k_norm = SDARRMSNorm(self.head_dim, eps=config.rms_norm_eps)
        self.attn_output_current = None
        self.attn_output_past = None
        self.logsumexp = None
        self.sliding_window = config.sliding_window
        if not (
            self.config.use_sliding_window
            and getattr(self.config, "sliding_window", None) is not None
            and self.layer_idx >= self.config.max_window_layers
        ):
            self.sliding_window = None


    def forward_flash_attn(self, query_states, key_states, value_states, attention_mask=None):
        """
        query_states, key_states, value_states: [B, L, H, D]
        attention_mask: [B, L]，1 表示有效，0 表示 pad（可选）
        """
        q = query_states
        k = key_states
        v = value_states
        B, L, Hq, D = q.shape
        _, _, Hk, _ = k.shape
        _, _, Hv, _ = v.shape
        device = q.device

        # ---- 情况1：无 mask，标准 FlashAttention ----
        if attention_mask is None:
            attn_output, logsumexp, _ = flash_attn_func(
                q, k, v,
                causal=False,
                return_attn_probs=True,
                softmax_scale=self.scaling,
            )
            return attn_output, logsumexp, _

        if attention_mask.dim() > 2:
            if attention_mask.shape[-2] != q.shape[1] or attention_mask.shape[-1] != k.shape[1]:
                raise ValueError(
                    "4D attention_mask shape must match query/key lengths: "
                    f"mask={tuple(attention_mask.shape)}, q_len={q.shape[1]}, k_len={k.shape[1]}"
                )
            score_mask = attention_mask.repeat(1, Hq, 1, 1).bool()
            block_mask = create_block_mask_cached(
                customize_mask(score_mask, block_size=1),
                B,
                Hq,
                q.shape[1],
                k.shape[1],
                device=device,
                _compile=False,
            )
            attn_output, logsumexp = flex_attention(
                q.transpose(1, 2),
                k.transpose(1, 2),
                v.transpose(1, 2).to(q),
                block_mask=block_mask,
                return_lse=True,
            )
            return attn_output.transpose(1, 2), logsumexp.transpose(1, 2)

        # ---- 情况2：有 mask，使用 varlen FlashAttention ----
        # Step 1. 计算每个样本有效 token 长度
        seqlens = attention_mask.sum(dim=-1, dtype=torch.int32)
        cu_seqlens = torch.cat([
            torch.zeros(1, dtype=torch.int32, device=device),
            seqlens.cumsum(dim=0)
        ]).int()

        # Step 2. 打包 Q/K/V（mask 过滤）
        q_packed = rearrange(q, "b l h d -> (b l) h d")
        kv = torch.stack([k, v], dim=2)  # [B, L, 2, Hk, D]
        kv_packed = rearrange(kv, "b l two h d -> (b l) two h d")[attention_mask.bool().flatten()]

        # Step 3. 调用 varlen kernel（新版接口要求两个 max_seqlen 参数）
        max_seqlen_q = q.size(1)
        max_seqlen_k = k.size(1)

        if max_seqlen_q == max_seqlen_k:
            cu_seqlens_q = cu_seqlens
            q_packed = q_packed[attention_mask.bool().flatten()]
        else:
            cu_seqlens_q = torch.range(0,q_packed.shape[0],L).to(cu_seqlens)
 
        attn_output, logsumexp, _ = flash_attn_varlen_kvpacked_func(
            q_packed,
            kv_packed,
            cu_seqlens_q, cu_seqlens,        # cu_seqlens_q, cu_seqlens_k
            max_seqlen_q, max_seqlen_k,    # ✅ 注意这里是两个位置参数！
            dropout_p=0.0,
            softmax_scale=self.scaling,
            causal=False,
            return_attn_probs=True
        )

        if max_seqlen_q == max_seqlen_k:
            out = torch.zeros((B, L, Hq, D), device=device, dtype=attn_output.dtype)
            out[attention_mask.bool()] = attn_output
            logsumexp_out = torch.zeros((B, L, Hq), device=device, dtype=logsumexp.dtype)
            logsumexp_out[attention_mask.bool()] = logsumexp.permute(1,0)
        else:
            out=attn_output.reshape(B, L, Hq, D)
            logsumexp_out = logsumexp.permute(1,0).reshape(B,L,Hq)

        return out, logsumexp_out

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: Tuple[torch.Tensor, torch.Tensor],
        attention_mask: Optional[torch.Tensor],
        past_key_value: Optional[Cache] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> Tuple[torch.Tensor, Optional[torch.Tensor], Optional[Tuple[torch.Tensor]]]:
        #0.0013
        sparsity_params = kwargs.get("sparsity_params",None)
        collect_attn_debug = kwargs.get("collect_attn_debug", False)
        if sparsity_params is not None:
            collect_attn_debug = sparsity_params.get("collect_attn_debug", collect_attn_debug)
        input_shape = hidden_states.shape[:-1]
        bsz, q_len = input_shape
        hidden_shape = (*input_shape, -1, self.head_dim)

        query_states = self.q_norm(self.q_proj(
            hidden_states).view(hidden_shape)).transpose(1, 2)
        key_states = self.k_norm(self.k_proj(
            hidden_states).view(hidden_shape)).transpose(1, 2)
        value_states = self.v_proj(hidden_states).view(
            hidden_shape).transpose(1, 2)
        
        # 0.0004

        cos, sin = position_embeddings
        query_states, key_states = apply_rotary_pos_emb(
            query_states, key_states, cos, sin)
        
        need_update_cache = True
        dirty_tokens=kwargs.get("dirty_tokens",None)

        #if sparsity_params is not None and sparsity_params["step"] > 0:
        #    if sparsity_params["layer_idx"]==0:
        #        influence = compute_token_influence(query_states,repeat_kv(key_states,   self.num_key_value_groups),scale=self.scaling,last_n=query_states.shape[2])
        #        if influence[sparsity_params["dirty_tokens"]].sum() < sparsity_params["sparsity_ratio"]:
        #            need_update_cache = False
        #        sparsity_params["need_update_cache"]=need_update_cache
        #    else:
        #        need_update_cache=sparsity_params["need_update_cache"]
        
        if sparsity_params is not None and sparsity_params.get("force_no_update_cache", False):
           need_update_cache = False
        elif sparsity_params is not None and sparsity_params["step"]>0 and len(sparsity_params["dirty_tokens"][0]) < sparsity_params["sparsity_ratio"]:
           need_update_cache = False
        if sparsity_params is not None and sparsity_params["step"]==0:
            self.coses=[]
            self.coses_per_head=[]
            self.cos_cures=[]
            self.cos_cures_per_head=[]

        # if sparsity_params is not None and sparsity_params["step"]>0 and sparsity_params["step"] % sparsity_params["sparsity_ratio"] == 1:
        #     need_update_cache = False

        if sparsity_params is not None:
            sparsity_params["need_update_cache"]=need_update_cache

        if attention_mask is None:
            key_states_, value_states_ = key_states, value_states
            if past_key_value is not None and kwargs.get("store_kv", False):
                # sin and cos are specific to RoPE models; cache_position needed for the static cache
                key_states, value_states = past_key_value.update(
                    key_states, value_states, self.layer_idx)
            elif past_key_value is not None and not kwargs.get("store_kv", False) and len(past_key_value) > self.layer_idx and not (sparsity_params is not None and not need_update_cache):
                # only retrive, do not store kv
                past_key_states, past_value_states = past_key_value[self.layer_idx]
                key_states = torch.cat(
                    [past_key_states, key_states], dim=-2)
                value_states = torch.cat(
                    [past_value_states, value_states], dim=-2)
        else:
            if past_key_value is not None and kwargs.get("store_kv", False):
                if kwargs.get("chunk_prefill", False):
                    # For chunk prefill, we want to append to the cache rather than overwriting.
                    # DynamicCache.update (inherited by DynamicCacheWithPadOverwrite) performs appending.
                    key_states, value_states = past_key_value.update(
                        key_states, value_states, self.layer_idx
                    )
                else:
                    # ✅ 覆盖式写入 (existing Trado/LLADA logic)
                    key_states, value_states = past_key_value.update_with_pad_overwrite(
                        key_states, value_states, self.layer_idx
                    )

            elif (
                past_key_value is not None
                and not kwargs.get("store_kv", False)
            ):
                # ✅ 只读合并
                if dirty_tokens is not None:
                    key_states_, value_states_ = key_states, value_states
                if need_update_cache:
                    append_to_cache = (
                        attention_mask is not None and attention_mask.dim() > 2
                    ) or (
                        sparsity_params is not None and sparsity_params.get("packed_probe", False)
                    )
                    key_states, value_states = past_key_value.merge_with_cache_for_inference(
                        key_states, value_states, self.layer_idx, attention_mask=attention_mask, append_to_cache=append_to_cache
                    )
                else:
                    attention_mask = sparsity_params.get("current_attention_mask", None) if sparsity_params is not None else None
            # else:
            #     attention_mask = None



        '''
        attention_mask = attention_mask.bool() if attention_mask is not None else None
        if torch.all(attention_mask):  # decoding
            query_states = query_states.transpose(1, 2)
            key_states = key_states.transpose(1, 2)
            value_states = value_states.transpose(1, 2)
            attn_output = flash_attn_func(
                query_states,
                key_states,
                value_states,
                causal=False,
                softmax_scale=self.scaling
            )

        else:  # prefilling
            attn_output = F.scaled_dot_product_attention(
                query=query_states,
                key=key_states,
                value=value_states,
                attn_mask=attention_mask,
                is_causal=False,
                scale=self.scaling,
                enable_gqa=True
            )
            attn_output = attn_output.transpose(1, 2).contiguous()
        '''

        #print(query_states.shape, key_states.shape, value_states.shape)

        #0.0002

        # --- After RoPE and KV-cache handling, expand KV to all heads ---
        key_states   = repeat_kv(key_states,   self.num_key_value_groups)  # [B, H, K, D]
        value_states = repeat_kv(value_states, self.num_key_value_groups)  # [B, H, K, D]

        sparsity_params = kwargs.get("sparsity_params",None)

        # --- Convert a 0/1 or bool 4D mask into an *additive* mask, and align to [B, H, Q, K] ---
        attn_mask = None
        # if attention_mask is not None:
        #     k_len = key_states.shape[-2]
        #     am = attention_mask
        #     # Support either 2D [B, K] or 4D [B, 1/H, Q, K]
        #     if am.dim() == 2:
        #         am = am[:, None, None, :k_len]             # -> [B,1,1,K]
        #     else:
        #         am = am[:, :, :, :k_len]                   # -> [B,1/H,Q,K]

        #     finfo_min = torch.finfo(query_states.dtype).min
        #     # 0/1 or bool -> float additive mask: 1->0, 0->-inf
        #     if am.dtype == torch.bool:
        #         zero   = torch.zeros((), dtype=query_states.dtype, device=am.device)
        #         neginf = torch.full((), finfo_min, dtype=query_states.dtype, device=am.device)
        #         am = torch.where(am, zero, neginf)
        #     else:
        #         # For 0/1 float masks: values > 0 are treated as visible
        #         am = am.to(query_states.dtype)
        #         am = torch.where(am > 0, torch.zeros_like(am), torch.full_like(am, finfo_min))

        #     # Expand to all heads
        #     #if am.shape[1] == 1 and self.num_attention_heads > 1:
        #     #    am = am.expand(am.shape[0], self.num_attention_heads, am.shape[2], am.shape[3])

        #     #attn_mask = am.contiguous()
        #     attn_mask = am
        

        bsz, q_len = input_shape


        if q_len == 1 and past_key_value is not None:
            # --- Decoding: flash-attn ---
            q = query_states.transpose(1, 2)  # [B,Q,H,D]
            k = key_states.transpose(1, 2)
            v = value_states.transpose(1, 2)
            attn_output = flash_attn_func(
                q, k, v,
                causal=True,                # For decoding, explicitly set causal=True
                softmax_scale=self.scaling
            )
            attn_output = attn_output.transpose(1, 2).contiguous()
        else:
            q = query_states.transpose(1, 2).contiguous()   # -> [B, Q, H, D]
            k = key_states.transpose(1, 2).contiguous()     # -> [B, K, H, D]
            v = value_states.transpose(1, 2).contiguous()   # -> [B, K, H, D]
#
            if attention_mask is None:
                attn_output, logsumexp, _ = flash_attn_func(
                    q, k, v,
                    causal=False,
                    return_attn_probs=True,
                    softmax_scale=self.scaling
                )
            else:
                if dirty_tokens is not None and not (sparsity_params is not None and sparsity_params.get("packed_probe", False)):
                    attn_output, logsumexp = self.forward_flash_attn(q,k,v,attention_mask)
                    key_states_   = repeat_kv(key_states_,   self.num_key_value_groups)  # [B, H, K, D]
                    value_states_ = repeat_kv(value_states_, self.num_key_value_groups)  # [B, H, K, D]
                    k_ = key_states_.transpose(1, 2).contiguous()     # -> [B, K, H, D]
                    v_ = value_states_.transpose(1, 2).contiguous()   # -> [B, K, H, D]
                    attn_output_, logsumexp_, _ = flash_attn_func(
                        q, k_, v_,
                        causal=False,
                        return_attn_probs=True,
                        softmax_scale=self.scaling
                    )
                    # dirty_mask: [B, Q] bool
                    dirty_mask = torch.zeros(
                        attn_output.shape[:2],
                        dtype=torch.bool,
                        device=attn_output.device
                    )

                    for b in range(len(dirty_tokens)):
                        dirty_mask[b, dirty_tokens[b]] = True

                    # 扩展到 [B, Q, 1, 1]
                    dirty_mask = dirty_mask[..., None, None]

                    attn_output = torch.where(
                        dirty_mask,
                        attn_output_,
                        attn_output
                    )
                else:
                    if len(attention_mask.shape)==2:
                        attn_output, logsumexp = self.forward_flash_attn(q,k,v,attention_mask)
                        logsumexp=logsumexp.transpose(1,2)
                    else:
                        # attn_output = F.scaled_dot_product_attention(
                        #     q.transpose(1,2),
                        #     k.transpose(1,2),
                        #     v.transpose(1,2),
                        #     attn_mask=attention_mask[:,None].repeat(1,q.shape[2],1,1),
                        #     dropout_p=0.0,
                        #     is_causal=False,
                        # ).transpose(1,2)
                        # attn_output=[]
                        # logsumexp=[]
                        # for i in range(bsz):
                        #     attn_output_, logsumexp_ = flashinfer.single_prefill_with_kv_cache(q[i], k[i], v[i],custom_mask=attention_mask[:,None].repeat(1,q.shape[2],1,1), causal=False,return_lse=True)
                        #     attn_output.append(attn_output_)
                        #     logsumexp.append(logsumexp_)
                        # attn_output=torch.stack(attn_output)
                        # logsumexp=torch.stack(logsumexp)
                        score_mask=attention_mask.repeat(1,q.shape[2],1,1).bool()
                        block_mask = create_block_mask_cached(customize_mask(score_mask, block_size=1), q.shape[0], q.shape[2], q.shape[1], k.shape[1], device=query_states.device, _compile=False)
                        attn_output, logsumexp = flex_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2).to(q),block_mask=block_mask,return_lse=True)
                        attn_output=attn_output.transpose(1,2)
            #exact_attn_output, exact_logsumexp, _ = exact_flash_attn_func(
            #    q, k, v,
            #    causal=False,
            #    return_attn_probs=True,
            #    softmax_scale=self.scaling
            #)
            #print(f"logsumexp diff {(exact_logsumexp-logsumexp).abs().max()}")
            if collect_attn_debug and k.shape[1] > query_states.shape[2]:
                cur_attn_output, cur_logsumexp, _ = flash_attn_func(
                    q, k[:,-query_states.shape[2]:], v[:,-query_states.shape[2]:],
                    causal=False,
                    return_attn_probs=True,
                    softmax_scale=self.scaling
                )
                if self.cur_attn_output is not None and cur_attn_output.shape[1] == self.cur_attn_output.shape[1]:
                    cos = F.cosine_similarity(cur_attn_output, self.cur_attn_output, dim=-1)
                    self.cos_cures.append(cos.mean().item())
                    self.cos_cures_per_head.append(cos.float().mean(dim=(0, 1)).detach().cpu().tolist())
                self.cur_attn_output=cur_attn_output.detach()
                past_attn_output, past_logsumexp, _ = flash_attn_func(
                    q, k[:,:-query_states.shape[2]], v[:,:-query_states.shape[2]],
                    causal=False,
                    return_attn_probs=True,
                    softmax_scale=self.scaling
                )
                if self.past_attn_output is not None and past_attn_output.shape[1] == self.past_attn_output.shape[1]:
                    cos = F.cosine_similarity(past_attn_output, self.past_attn_output, dim=-1)
                    self.coses.append(cos.mean().item())
                    self.coses_per_head.append(cos.float().mean(dim=(0, 1)).detach().cpu().tolist())
                self.past_attn_output=past_attn_output.detach()
            if sparsity_params is not None:
                if need_update_cache:
                    #current_attn_output, current_logsumexp, _ = flash_attn_func(
                    #    q, k[:,-query_states.shape[2]:], v[:,-query_states.shape[2]:],
                    #    causal=False,
                    #    return_attn_probs=True,
                    #    softmax_scale=self.scaling
                    #)
                    if attention_mask is None:
                        past_attn_output, past_logsumexp, _ = flash_attn_func(
                            q, k[:,:-query_states.shape[2]], v[:,:-query_states.shape[2]],
                            causal=False,
                            return_attn_probs=True,
                            softmax_scale=self.scaling
                        )
                    else:
                        # past_attn_output=[]
                        # past_logsumexp=[]
                        # for i in range(bsz):
                        #     attn_output_, logsumexp_ = flashinfer.single_prefill_with_kv_cache(q[i], k[i], v[i],custom_mask=sparsity_params["attn_mask_outer"][:,None].repeat(1,q.shape[2],1,1), causal=False,return_lse=True)
                        #     past_attn_output.append(attn_output_)
                        #     past_logsumexp.append(logsumexp_)
                        # past_attn_output=torch.stack(past_attn_output)
                        # past_logsumexp=torch.stack(past_logsumexp)

                        # score_mask=sparsity_params["attn_mask_outer"][:,None].repeat(1,q.shape[2],1,1)
                        # block_mask = create_block_mask_cached(customize_mask(score_mask, block_size=1), q.shape[0], q.shape[2], q.shape[1], k.shape[1], device=query_states.device, _compile=False)
                        # past_attn_output, past_logsumexp = flex_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2).to(q),block_mask=block_mask,return_lse=True)
                        # past_attn_output=past_attn_output.transpose(1,2)

                        past_attention_mask = sparsity_params.get("past_attention_mask", None)
                        if past_attention_mask is None:
                            past_attention_mask = torch.zeros(
                                (bsz, 1, q.shape[1], k.shape[1]),
                                dtype=torch.float32,
                                device=query_states.device,
                            )
                            if attention_mask.dim() > 2:
                                past_attention_mask = attention_mask[:, :, :, : k.shape[1]].to(
                                    device=query_states.device, dtype=torch.float32
                                )
                                past_attention_mask[:, :, :, -q.shape[1]:] = 0.0
                            else:
                                prefix_lens = attention_mask.sum(dim=-1).to(torch.long) - q.shape[1]
                                prefix_lens = prefix_lens.clamp(min=0, max=k.shape[1] - q.shape[1])
                                for b in range(bsz):
                                    past_attention_mask[b, :, :, : prefix_lens[b].item()] = 1.0
                        past_attn_output, past_logsumexp = self.forward_flash_attn(q,k,v,past_attention_mask)
                        past_logsumexp = past_logsumexp.transpose(1, 2)
                    # 转置、升精度
                    # current_logsumexp = current_logsumexp.double().transpose(1, 2).unsqueeze(-1)

                    # 按缩放后重建 past 的分子分母（在稳定区间）

                    # key_states_   = repeat_kv(key_states_,   self.num_key_value_groups)  # [B, H, K, D]
                    # value_states_ = repeat_kv(value_states_, self.num_key_value_groups)  # [B, H, K, D]
                    # k_ = key_states_.transpose(1, 2).contiguous()     # -> [B, K, H, D]
                    # v_ = value_states_.transpose(1, 2).contiguous()   # -> [B, K, H, D]
                    # attn_output_, logsumexp_, _ = flash_attn_func(
                    #     q, k_, v_,
                    #     causal=False,
                    #     return_attn_probs=True,
                    #     softmax_scale=self.scaling
                    # )
                    self.attn_output_past = past_attn_output.double()
                    past_logsumexp=past_logsumexp.transpose(1,2).unsqueeze(-1).double()
                    # self.attn_output_=attn_output_


                    self.logsumexp = past_logsumexp
                    self.logsumexp_all = logsumexp.transpose(1,2).unsqueeze(-1).double()

                else:
                    # === 奇数步 ===
                    # 已经有当前的 attn_output, logsumexp 是 current 的
                    current_logsumexp = logsumexp.float().transpose(1, 2).unsqueeze(-1)
                    current_attn_output = attn_output
                    past_logsumexp = self.logsumexp
                    
                    # 数值稳定处理
                    # 数值稳定合并 past/current
                    # past_logsumexp[past_logsumexp.isinf()]=0
                    # past_logsumexp[past_logsumexp.isinf()]=0
                    # past_logsumexp = torch.nan_to_num(past_logsumexp, nan=1.0, posinf=1.0, neginf=1.0)
                    # current_logsumexp  = torch.nan_to_num(current_logsumexp,  nan=1.0, posinf=1.0, neginf=1.0)
                    
                    m = torch.maximum(past_logsumexp, current_logsumexp)        # [B,H,Q,1]
                    exp_past = torch.exp(past_logsumexp - m)
                    exp_cur  = torch.exp(current_logsumexp - m)

                    # exp_past=zero_dirty_tokens(exp_past,sparsity_params["dirty_tokens"])
                    denom = (exp_past + exp_cur)

                    # self.attn_output_past=zero_dirty_tokens(self.attn_output_past,sparsity_params["dirty_tokens"])
                    veri_attn_output = (
                        (current_attn_output * exp_cur + self.attn_output_past * exp_past) / denom
                    )

                    # veri_attn_output[:,sparsity_params["dirty_tokens"]]=current_attn_output[:,sparsity_params["dirty_tokens"]].to(veri_attn_output)
                    #veri_attn_output = assign_sparse_tokens(veri_attn_output, current_attn_output, sparsity_params["dirty_tokens"])
                    #print((attn_output-veri_attn_output).abs().max())
                    attn_output=veri_attn_output.to(query_states)
                    self.attn_output_past = None
                    self.logsumexp = None
                    self.logsumexp_all = None
                    # attn_output=torch.where(create_dirty_mask(exp_past,sparsity_params["dirty_tokens"])[...,None,None],veri_attn_output,current_attn_output).to(query_states)

            # attn_output = attn_output.transpose(1, 2).contiguous()  # -> [B,Q,H,D]

        attn_output = attn_output.reshape(*input_shape, -1).contiguous().to(query_states)
        attn_output = self.o_proj(attn_output)
        return attn_output, None  # , attn_weights


class SDARDecoderLayer(GradientCheckpointingLayer):
    def __init__(self, config: SDARConfig, layer_idx: int):
        super().__init__()
        self.hidden_size = config.hidden_size
        self.self_attn = SDARAttention(config=config, layer_idx=layer_idx)
        self.mlp = SDARMLP(config)
        self.input_layernorm = SDARRMSNorm(
            config.hidden_size, eps=config.rms_norm_eps)
        self.post_attention_layernorm = SDARRMSNorm(
            config.hidden_size, eps=config.rms_norm_eps)
        if (
            config.sliding_window and config._attn_implementation != "flash_attention_2"
        ):  # diff with Llama is this warning
            logger.warning_once(
                f"Sliding Window Attention is enabled but not implemented for `{config._attn_implementation}`; "
                "unexpected results may be encountered."
            )

    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_value: Optional[Cache] = None,
        output_attentions: Optional[bool] = False,
        use_cache: Optional[bool] = False,
        store_kv: Optional[bool] = False,
        cache_position: Optional[torch.LongTensor] = None,
        # necessary, but kept here for BC
        position_embeddings: Optional[Tuple[torch.Tensor,
                                            torch.Tensor]] = None,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> Tuple[torch.FloatTensor, Optional[Tuple[torch.FloatTensor, torch.FloatTensor]]]:
        residual = hidden_states
        hidden_states = self.input_layernorm(hidden_states)

        # Self Attention
        hidden_states, self_attn_weights = self.self_attn(
            hidden_states=hidden_states,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_value=past_key_value,
            output_attentions=output_attentions,
            use_cache=use_cache,
            store_kv=store_kv,
            cache_position=cache_position,
            position_embeddings=position_embeddings,
            **kwargs,
        )
        hidden_states = residual + hidden_states

        # Fully Connected
        residual = hidden_states
        hidden_states = self.post_attention_layernorm(hidden_states)
        hidden_states = self.mlp(hidden_states)
        hidden_states = residual + hidden_states

        outputs = (hidden_states,)
        if output_attentions:
            outputs += (self_attn_weights,)

        return outputs

import torch
import matplotlib.pyplot as plt
import seaborn as sns
import os

def visualize_multihead_attention(q, k, v, attention_bias=None, save_dir="./att_vis"):
    """
    可视化并保存多头 attention 的权重矩阵。
    
    参数:
        q, k, v: 注意力输入张量，形状 [batch, head, seq_len, dim]
        attention_bias: 注意力偏置，可选
        save_dir: 保存图片的目录
    """
    # 1. 计算 scaled dot-product attention 分数
    attn_scores = torch.matmul(q, k.transpose(-2, -1)) / (q.size(-1) ** 0.5)
    if attention_bias is not None:
        attn_scores += attention_bias

    # 2. softmax 得到注意力权重
    attn_weights = torch.softmax(attn_scores, dim=-1)  # [B, H, N, N]

    # 3. 计算注意力输出（可选）
    att = torch.matmul(attn_weights, v)

    # 4. 创建保存目录
    os.makedirs(save_dir, exist_ok=True)

    # 5. 遍历每个 head，生成热力图
    num_heads = attn_weights.size(1)
    for h in range(num_heads):
        plt.figure(figsize=(6, 5))
        sns.heatmap(attn_weights[0, h].float().detach().cpu().numpy(), cmap="viridis")
        plt.title(f"Attention Head {h}")
        plt.xlabel("Key positions")
        plt.ylabel("Query positions")
        save_path = os.path.join(save_dir, f"head_{h}.png")
        plt.savefig(save_path, bbox_inches='tight')
        plt.close()

    print(f"✅ 保存完成，共 {num_heads} 个注意力头，图像目录: {save_dir}")
    return att


@auto_docstring
class SDARPreTrainedModel(PreTrainedModel):
    config_class = SDARConfig
    base_model_prefix = "model"
    supports_gradient_checkpointing = True
    _no_split_modules = ["SDARDecoderLayer"]
    _skip_keys_device_placement = ["past_key_values"]
    _supports_flash_attn_2 = True
    _supports_sdpa = True
    _supports_flex_attn = True
    _supports_cache_class = True
    _supports_quantized_cache = True
    _supports_static_cache = True
    _supports_attention_backend = True

    def _init_weights(self, module):
        std = self.config.initializer_range
        if isinstance(module, nn.Linear):
            module.weight.data.normal_(mean=0.0, std=std)
            if module.bias is not None:
                module.bias.data.zero_()
        elif isinstance(module, nn.Embedding):
            module.weight.data.normal_(mean=0.0, std=std)
            if module.padding_idx is not None:
                module.weight.data[module.padding_idx].zero_()
        elif isinstance(module, SDARRMSNorm):
            module.weight.data.fill_(1.0)


class SDARRotaryEmbedding(nn.Module):
    def __init__(self, config: SDARConfig, device=None):
        super().__init__()
        # BC: "rope_type" was originally "type"
        if hasattr(config, "rope_scaling") and config.rope_scaling is not None:
            self.rope_type = config.rope_scaling.get(
                "rope_type", config.rope_scaling.get("type"))
        else:
            self.rope_type = "default"
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings

        self.config = config
        self.rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]

        inv_freq, self.attention_scaling = self.rope_init_fn(
            self.config, device)
        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.original_inv_freq = self.inv_freq

    @torch.no_grad()
    # power user: used with advanced RoPE types (e.g. dynamic rope)
    @dynamic_rope_update
    def forward(self, x, position_ids):
        inv_freq_expanded = self.inv_freq[None, :, None].float().expand(
            position_ids.shape[0], -1, 1).to(x.device)
        position_ids_expanded = position_ids[:, None, :].float()

        device_type = x.device.type if isinstance(
            x.device.type, str) and x.device.type != "mps" else "cpu"
        with torch.autocast(device_type=device_type, enabled=False):  # Force float32
            freqs = (inv_freq_expanded.float() @
                     position_ids_expanded.float()).transpose(1, 2)
            emb = torch.cat((freqs, freqs), dim=-1)
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


@auto_docstring
class SDARModel(SDARPreTrainedModel):
    def __init__(self, config: SDARConfig):
        super().__init__(config)
        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size

        self.embed_tokens = nn.Embedding(
            config.vocab_size, config.hidden_size, self.padding_idx)
        self.layers = nn.ModuleList(
            [SDARDecoderLayer(config, layer_idx)
             for layer_idx in range(config.num_hidden_layers)]
        )
        self.norm = SDARRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.rotary_emb = SDARRotaryEmbedding(config=config)
        self.gradient_checkpointing = False

        # Initialize weights and apply final processing
        self.post_init()

    def get_input_embeddings(self):
        return self.embed_tokens

    def set_input_embeddings(self, value):
        self.embed_tokens = value

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        use_cache: Optional[bool] = None,
        store_kv: Optional[bool] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **flash_attn_kwargs: Unpack[FlashAttentionKwargs],
    ) -> BaseModelOutputWithPast:
        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )
        use_cache = use_cache if use_cache is not None else self.config.use_cache

        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError(
                "You must specify exactly one of input_ids or inputs_embeds")

        if self.gradient_checkpointing and self.training and use_cache:
            logger.warning_once(
                "`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`."
            )
            use_cache = False

        # TODO (joao): remove this exception in v4.56 -- it exists for users that try to pass a legacy cache
        if not isinstance(past_key_values, (type(None), Cache)):
            raise ValueError(
                "The `past_key_values` should be either a `Cache` object or `None`.")

        if inputs_embeds is None:
            inputs_embeds = self.embed_tokens(input_ids)

        if use_cache and past_key_values is None:
            past_key_values = DynamicCache()

        if cache_position is None:
            past_seen_tokens = past_key_values.get_seq_length(
            ) if past_key_values is not None else 0
            cache_position = torch.arange(
                past_seen_tokens, past_seen_tokens + inputs_embeds.shape[1], device=inputs_embeds.device
            )

        if position_ids is None:
            position_ids = cache_position.unsqueeze(0)

        # causal_mask = self._update_causal_mask(
        #     attention_mask, inputs_embeds, cache_position, past_key_values, output_attentions
        # )

        hidden_states = inputs_embeds

        # create position embeddings to be shared across the decoder layers
        position_embeddings = self.rotary_emb(hidden_states, position_ids)

        # decoder layers
        all_hidden_states = () if output_hidden_states else None
        all_self_attns = () if output_attentions else None

        for layer_idx,decoder_layer in enumerate(self.layers[: self.config.num_hidden_layers]):
            if output_hidden_states:
                all_hidden_states += (hidden_states,)

            if "sparsity_params" in flash_attn_kwargs and flash_attn_kwargs["sparsity_params"] is not None:
                flash_attn_kwargs["sparsity_params"]["layer_idx"]=layer_idx

            layer_outputs = decoder_layer(
                hidden_states,
                attention_mask=attention_mask,
                position_ids=position_ids,
                past_key_value=past_key_values,
                output_attentions=output_attentions,
                use_cache=use_cache,
                store_kv=store_kv,
                cache_position=cache_position,
                position_embeddings=position_embeddings,
                **flash_attn_kwargs,
            )

            hidden_states = layer_outputs[0]

            if output_attentions:
                all_self_attns += (layer_outputs[1],)

        hidden_states = self.norm(hidden_states)

        # add hidden states from the last decoder layer
        if output_hidden_states:
            all_hidden_states += (hidden_states,)

        return BaseModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values if use_cache else None,
            hidden_states=all_hidden_states,
            attentions=all_self_attns,
        )

    def _update_causal_mask(
        self,
        attention_mask: Union[torch.Tensor, "BlockMask"],
        input_tensor: torch.Tensor,
        cache_position: torch.Tensor,
        past_key_values: Cache,
        output_attentions: bool = False,
    ):
        if self.config._attn_implementation == "flash_attention_2":
            if attention_mask is not None and past_key_values is not None:
                is_padding_right = attention_mask[:, -
                                                  1].sum().item() != input_tensor.size()[0]
                if is_padding_right:
                    raise ValueError(
                        "You are attempting to perform batched generation with padding_side='right'"
                        " this may lead to unexpected behaviour for Flash Attention version of Qwen3. Make sure to "
                        " call `tokenizer.padding_side  = 'left'` before tokenizing the input. "
                    )
            if attention_mask is not None and 0.0 in attention_mask:
                return attention_mask
            return None
        if self.config._attn_implementation == "flex_attention":
            if isinstance(attention_mask, torch.Tensor):
                seq_len_q, seq_len_kv = attention_mask.shape
                assert seq_len_q == seq_len_kv, f"got {attention_mask.shape=}"
                attention_mask = create_block_mask(
                    # 2d bool tensor, shape: [2*seqlen, 2*seqlen]
                    lambda b, h, q_idx, kv_idx: attention_mask[q_idx, kv_idx],
                    B=None, H=None, Q_LEN=seq_len_q, KV_LEN=seq_len_kv,
                )
            else:
                # Here we pass in flex mask computed externally
                assert isinstance(attention_mask, BlockMask)
            return attention_mask

        # For SDPA, when possible, we will rely on its `is_causal` argument instead of its `attn_mask` argument, in
        # order to dispatch on Flash Attention 2. This feature is not compatible with static cache, as SDPA will fail
        # to infer the attention mask.
        past_seen_tokens = past_key_values.get_seq_length(
        ) if past_key_values is not None else 0
        using_static_cache = isinstance(past_key_values, StaticCache)
        using_sliding_window_cache = isinstance(
            past_key_values, SlidingWindowCache)

        # When output attentions is True, sdpa implementation's forward method calls the eager implementation's forward
        if (
            self.config._attn_implementation == "sdpa"
            and not (using_static_cache or using_sliding_window_cache)
            and not output_attentions
        ):
            if AttentionMaskConverter._ignore_causal_mask_sdpa(
                attention_mask,
                inputs_embeds=input_tensor,
                past_key_values_length=past_seen_tokens,
                sliding_window=self.config.sliding_window,
                is_training=self.training,
            ):
                return None

        dtype = input_tensor.dtype
        min_dtype = torch.finfo(dtype).min
        sequence_length = input_tensor.shape[1]
        # SlidingWindowCache or StaticCache
        if using_sliding_window_cache or using_static_cache:
            target_length = past_key_values.get_max_cache_shape()
        # DynamicCache or no cache
        else:
            target_length = (
                attention_mask.shape[-1]
                if isinstance(attention_mask, torch.Tensor)
                else past_seen_tokens + sequence_length + 1
            )

        # In case the provided `attention` mask is 2D, we generate a causal mask here (4D).
        causal_mask = self._prepare_4d_causal_attention_mask_with_cache_position(
            attention_mask,
            sequence_length=sequence_length,
            target_length=target_length,
            dtype=dtype,
            cache_position=cache_position,
            batch_size=input_tensor.shape[0],
            config=self.config,
            past_key_values=past_key_values,
        )

        if (
            self.config._attn_implementation == "sdpa"
            and attention_mask is not None
            and attention_mask.device.type in ["cuda", "xpu", "npu"]
            and not output_attentions
        ):
            # Attend to all tokens in fully masked rows in the causal_mask, for example the relevant first rows when
            # using left padding. This is required by F.scaled_dot_product_attention memory-efficient attention path.
            # Details: https://github.com/pytorch/pytorch/issues/110213
            causal_mask = AttentionMaskConverter._unmask_unattended(
                causal_mask, min_dtype)

        return causal_mask

    @staticmethod
    def _prepare_4d_causal_attention_mask_with_cache_position(
        attention_mask: torch.Tensor,
        sequence_length: int,
        target_length: int,
        dtype: torch.dtype,
        cache_position: torch.Tensor,
        batch_size: int,
        config: SDARConfig,
        past_key_values: Cache,
    ):
        """
        Creates a causal 4D mask of shape `(batch_size, 1, query_length, key_value_length)` from a 2D mask of shape
        `(batch_size, key_value_length)`, or if the input `attention_mask` is already 4D, do nothing.
        Args:
            attention_mask (`torch.Tensor`):
                A 2D attention mask of shape `(batch_size, key_value_length)` or a 4D attention mask of shape `(batch_size, 1, query_length, key_value_length)`.
            sequence_length (`int`):
                The sequence length being processed.
            target_length (`int`):
                The target length: when generating with static cache, the mask should be as long as the static cache, to account for the 0 padding, the part of the cache that is not filled yet.
            dtype (`torch.dtype`):
                The dtype to use for the 4D attention mask.
            cache_position (`torch.Tensor`):
                Indices depicting the position of the input sequence tokens in the sequence.
            batch_size (`torch.Tensor`):
                Batch size.
            config (`SDARConfig`):
                The model's configuration class
            past_key_values (`Cache`):
                The cache class that is being used currently to generate
        """
        if attention_mask is not None and attention_mask.dim() == 4:
            # In this case we assume that the mask comes already in inverted form and requires no inversion or slicing.
            causal_mask = attention_mask
        else:
            min_dtype = torch.finfo(dtype).min
            causal_mask = torch.full(
                (sequence_length, target_length), fill_value=min_dtype, dtype=dtype, device=cache_position.device
            )
            diagonal_attend_mask = torch.arange(target_length, device=cache_position.device) > cache_position.reshape(
                -1, 1
            )
            text_config = config.get_text_config()
            if getattr(text_config, "use_sliding_window", True) and text_config.sliding_window is not None:
                # if we have sliding window, we should not attend to tokens beyond sliding window length, so we mask them out also
                # the check is needed to verify is current checkpoint was trained with sliding window or not
                if not isinstance(past_key_values, SlidingWindowCache) or sequence_length > target_length:
                    sliding_attend_mask = torch.arange(target_length, device=cache_position.device) <= (
                        cache_position.reshape(-1, 1) -
                        text_config.sliding_window
                    )
                    diagonal_attend_mask.bitwise_or_(sliding_attend_mask)
            causal_mask *= diagonal_attend_mask
            causal_mask = causal_mask[None, None,
                                      :, :].expand(batch_size, 1, -1, -1)
            if attention_mask is not None:
                causal_mask = causal_mask.clone()  # copy to contiguous memory for in-place edit
                if attention_mask.shape[-1] > target_length:
                    attention_mask = attention_mask[:, :target_length]
                mask_length = attention_mask.shape[-1]
                padding_mask = causal_mask[:, :, :, :mask_length] + attention_mask[:, None, None, :].to(
                    causal_mask.device
                )
                padding_mask = padding_mask == 0
                causal_mask[:, :, :, :mask_length] = causal_mask[:, :, :, :mask_length].masked_fill(
                    padding_mask, min_dtype
                )
        return causal_mask


class KwargsForCausalLM(FlashAttentionKwargs, LossKwargs):
    ...


@auto_docstring
class SDARForCausalLM(SDARPreTrainedModel, GenerationMixin):
    _tied_weights_keys = ["lm_head.weight"]
    _tp_plan = {"lm_head": "colwise_rep"}
    _pp_plan = {"lm_head": (["hidden_states"], ["logits"])}

    def __init__(self, config):
        super().__init__(config)
        self.model = SDARModel(config)
        self.vocab_size = config.vocab_size
        self.lm_head = nn.Linear(
            config.hidden_size, config.vocab_size, bias=False)

        # Initialize weights and apply final processing
        self.post_init()

    def get_input_embeddings(self):
        return self.model.embed_tokens

    def set_input_embeddings(self, value):
        self.model.embed_tokens = value

    def get_output_embeddings(self):
        return self.lm_head

    def set_output_embeddings(self, new_embeddings):
        self.lm_head = new_embeddings

    def set_decoder(self, decoder):
        self.model = decoder

    def get_decoder(self):
        return self.model

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        logits_to_keep: Union[int, torch.Tensor] = 0,
        **kwargs: Unpack[KwargsForCausalLM],
    ) -> CausalLMOutputWithPast:
        r"""
        labels (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
            Labels for computing the masked language modeling loss. Indices should either be in `[0, ...,
            config.vocab_size]` or -100 (see `input_ids` docstring). Tokens with indices set to `-100` are ignored
            (masked), the loss is only computed for the tokens with labels in `[0, ..., config.vocab_size]`.
        Example:
        ```python
        >>> from transformers import AutoTokenizer, SDARForCausalLM
        >>> model = SDARForCausalLM.from_pretrained("DiffuOpen/SDAR-1.7B-Chat")
        >>> tokenizer = AutoTokenizer.from_pretrained("DiffuOpen/SDAR-1.7B-Chat")
        >>> prompt = "Hey, are you conscious? Can you talk to me?"
        >>> inputs = tokenizer(prompt, return_tensors="pt")
        >>> # Generate
        >>> generate_ids = model.generate(inputs.input_ids, max_length=30)
        >>> tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
        "Hey, are you conscious? Can you talk to me?\nI'm not conscious, but I can talk to you."
        ```"""
        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )

        # decoder outputs consists of (dec_features, layer_state, dec_hidden, dec_attn)
        outputs: BaseModelOutputWithPast = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            cache_position=cache_position,
            **kwargs,
        )

        hidden_states = outputs.last_hidden_state
        # Only compute necessary logits, and do not upcast them to float if we are not computing the loss
        slice_indices = slice(-logits_to_keep,
                              None) if isinstance(logits_to_keep, int) else logits_to_keep
        hidden_states = hidden_states[:, slice_indices, :].contiguous()
        fuse_linear_and_cross_entropy = self.config.fuse_cross_entropy and self.training
        if fuse_linear_and_cross_entropy:
            # When using fused_linear_ce_loss, we do not compute the whole logits on HBM
            logits = None
        else:
            logits = self.lm_head(hidden_states)

        loss = None
        if labels is not None:
            # FusedLinearCrossEntropyLoss will be implemented by monkey patch when training
            # We don't use it when inferencing
            loss_fct = nn.CrossEntropyLoss()  # nn.CE
            loss = loss_fct(
                logits.view(-1, self.config.vocab_size), labels.view(-1))

        return CausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
        )


__all__ = [
    "SDARForCausalLM",
    "SDARModel",
    "SDARPreTrainedModel",
]
